# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master

resources:
  containers:
  - container: redis
    image: redis

jobs:
- job: 'buildTestPack'
  displayName: 'build test and pack'
  pool:
    vmImage: 'ubuntu-latest'
  container: mcr.microsoft.com/dotnet/core/sdk:3.0
  services:
    redis: redis
  variables:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    CONNECTIONSTRINGS_REDIS: 'redis:6379' 
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration release'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: 'test'
      projects: '**/*.Tests.csproj'
      arguments: '--collect "Xplat code coverage"'
      nobuild: true
  - task: DotNetCoreCLI@2
    displayName: 'dotnet pack'
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      includesymbols: true
      includesource: true
      versioningScheme: 'off'
      nobuild: true
  - publish: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;'
    artifact: Packages
- job: 'nuget'
  displayName: 'Nuget'
  steps:
  - task: NuGetCommand@2
    displayName: 'nuget push to local feed'
    inputs:
      command: 'push'
      packagesToPush: Packages
      nuGetFeedType: 'internal'
      publishVstsFeed: 'TestNugetFeed'
      allowPackageConflicts: true
    condition: succeeded()

  - task: NuGetCommand@2
    displayName: 'nuget push to nuget.org on tag'
    inputs:
      command: 'push'
      packagesToPush: Packages
      nuGetFeedType: 'external'
      publishFeedCredentials: 'NugetConnection'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))